# Generated by Django 3.0.4 on 2020-10-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DumboUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Id')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('fullname', models.CharField(max_length=255, verbose_name='Fullname')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Date Joined')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Phone number')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
