# Generated by Django 3.1.2 on 2020-11-03 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('twitter_link', models.URLField(default='', null=True)),
                ('total_docs', models.IntegerField(default=None, null=True)),
                ('in_trash', models.IntegerField(default=None, null=True)),
                ('public_docs', models.IntegerField(default=None, null=True)),
                ('total_space', models.FloatField(default=None, null=True)),
                ('used_space', models.FloatField(default=None, null=True)),
                ('important_docs', models.IntegerField(default=None, null=True)),
                ('important_tags', models.CharField(default=None, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
