# Generated by Django 3.1.2 on 2020-11-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://storage.googleapis.com/dumbo-document-storage/profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
