# Generated by Django 3.1.2 on 2020-11-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201105_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_space',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='used_space',
            field=models.FloatField(default=0, null=True),
        ),
    ]
