# Generated by Django 3.1.2 on 2020-11-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201105_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='in_trash',
            field=models.IntegerField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_docs',
            field=models.IntegerField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_docs',
            field=models.IntegerField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_space',
            field=models.FloatField(default=2000000000.0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='used_space',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
