# Generated by Django 3.1.2 on 2020-11-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201122_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_space',
            field=models.FloatField(default=50000000.0, null=True),
        ),
    ]
