# Generated by Django 3.1.2 on 2020-11-09 15:15

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20201029_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='path',
            field=models.FileField(upload_to=documents.models.update_filename),
        ),
    ]
