# Generated by Django 3.1.2 on 2020-11-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20201109_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='in_trash',
            field=models.BooleanField(default=False),
        ),
    ]
