# Generated by Django 3.1.2 on 2020-11-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_in_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
