# Generated by Django 3.1.2 on 2020-11-18 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20201117_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='thumbs',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='documents.document')),
                ('image', models.ImageField(default='https://storage.googleapis.com/dumbo-document-storage/thumbnails/documents/default.svg', upload_to='thumbnails/')),
            ],
        ),
    ]
