# Generated by Django 3.1.2 on 2020-11-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20201118_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
