# Generated by Django 3.1.2 on 2020-11-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_document_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='view_count',
        ),
    ]
